apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HOulcaid/gcp-gke-gitops
    targetRevision: HEAD
    path: app/monitoring/kubecost
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true